#!/bin/bash

echo Script Start
date

python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1068	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1068.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1147	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1147.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1164	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1164.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1206	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1206.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1332	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1332.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1372	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1372.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1374	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1374.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1464	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1464.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1549	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1549.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1622	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1622.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1666	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1666.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1751	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1751.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1769	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1769.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1786	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1786.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1831	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1831.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_1960	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_1960.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_2000	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_2000.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_2100	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_2100.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_2580	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_2580.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_2776	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_2776.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_2787	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_2787.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_3515	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_3515.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_3557	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_3557.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4151	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4151.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4287	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4287.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4302	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4302.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4397	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4397.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4404	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4404.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4491	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4491.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4654	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4654.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4727	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4727.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4818	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4818.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_4988	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_4988.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_5238	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_5238.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_5458	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_5458.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_5623	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_5623.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_5826	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_5826.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_5838	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_5838.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_6025	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_6025.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_6172	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_6172.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_6215	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_6215.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_6318	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_6318.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_6445	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_6445.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_6807	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_6807.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_7234	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_7234.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_7384	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_7384.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_7965	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_7965.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_8124	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_8124.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_8128	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_8128.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_8265	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_8265.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_8440	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_8440.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_8540	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_8540.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_8973	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_8973.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_9296	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_9296.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_9655	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_9655.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_9702	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_9702.log
python predict_regression.py -f /srv/ta_data/deployment_features_pickles/all_access_wireless_traceroute/test_9892	 -p /srv/ta_data/inference_pickles/all_access_wireless_traceroute/startup -t startup > ./Log_files_startup/test_9892.log


echo Script End
date
